[pytest]
pythonpath = backend
filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:fastapi.*
markers =
    asyncio: mark a test as asyncio to run with pytest-asyncio